# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#

require "simplecov"
require "webmock/rspec"
require "vcr"

SimpleCov.coverage_dir("reports/simplecov")
SimpleCov.start

# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.filter_run_when_matching :focus

  config.shared_context_metadata_behavior = :apply_to_host_groups

  if config.files_to_run.one?
    config.default_formatter = "doc"
  else
    config.profile_examples = 10
  end

  config.order = :random
  Kernel.srand config.seed

  $now = Time.parse("2020-01-01 00:00:01-01:00")

  config.around do |example|
    Timecop.travel($now) do
      example.run
    end
  end

  VCR.configure do |config|
    config.cassette_library_dir = "spec/support/vcr_cassettes"
    config.hook_into :webmock

    config.ignore_hosts "127.0.0.1", "localhost"

    config.filter_sensitive_data("<AUTHORIZATION>") do |interaction|
      interaction.request.headers["Authorization"]&.first
    end
  end
end
